development:
 adapter: postgresql
 encoding: unicode
 database: logistic_development
 username: inmobi
 password:
 host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: logistic_production
  username: postgres
  password: xxxxxxxxxx
  host: localhost

# development:
#   adapter: sqlite3
#   database: db/db_dev_db.sqlite3
#   pool: 5
#   timeout: 5000

# production:
#   adapter: sqlite3
#   database: db/db_dev_db.sqlite3
#   pool: 5
#   timeout: 5000


#production:
#  adapter: postgresql
#  database: logistic_production
#  pool: 5
#  encoding: unicode
#  #host: localhost
#  port: 5432
#  username: postgres
#  password: 123456